/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arquitectura.hexagonal.gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author rober
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        cargaGrafica();
    }

    public void cargaGrafica() {
        FileReader fr = null;
        int cont = 1;
        String part1;
        String part2;
        String part3;
        String part4;
        String part5;
        String part6;
        ArrayList<String> datos = new ArrayList<>();
        try {
            File file = new File("/Users/christianfebres/Downloads/prueba.txt");
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String lines = "";
            int contAux= 0;
            while ((lines = br.readLine()) != null) {
                System.out.println("bandera");
                if (cont > 10) {
                    for (int i = 0; i < 5; i++) {
                        System.out.println("badera");
                        System.out.println(lines);
                        String[] parts = lines.split("\\s+");
                        part1 = parts[i]; // 123
                        System.out.println(part1);
                        datos.add(part1);
                    }
                    //part1 = parts[0]; // 123
//                    part2 = parts[1]; // 654321
//                    part3 = parts[2]; // 123
//                    part4 = parts[3]; // 654321
//                    part5 = parts[4]; // 123
//                    part6 = parts[5]; // 654321
                    //datos.add(part1);
//                    datos.add(part2);
//                    datos.add(part3);
//                    datos.add(part4);
//                    datos.add(part5);
//                    datos.add(part6);
                    }
                cont++;
            }
            System.out.println(datos);
            XYSeries series = new XYSeries("");
         
            //Generador aleatorio binario
            for (int i = 0; i < cont; i++) {
                series.add(i, Double.parseDouble(datos.get(i)));

            }
            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(series);
            JFreeChart chart = ChartFactory.createXYLineChart(
                    "Grafica archivo prueba",
                    "Número de Ciclos",
                    "Acelerógrafo",
                    dataset,
                    PlotOrientation.VERTICAL,
                    false,
                    false,
                    false
            );  // Mostramos la grafica en pantalla
            ChartFrame frame = new ChartFrame("Ejemplo Grafica Lineal", chart);
            frame.pack();
            frame.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
